spring:
  datasource:
    url: jdbc:mariadb://133.186.153.136:3306/op_7b7bf585_d1ab_4d19_8bb1_42f50e4e37e6
    username: 841dcc9e8d0fbec1
    password: e2692e56b80ced50
    driver-class-name: org.mariadb.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
mybatis:
  config-location: classpath:mybatis-config.xml
api:
  type: json
  key: sample

---
spring:
  profiles: cloud
api:
  type: json
  key: 0090a9d2727bba40209dceda6622021138a5746728d91bc567f43021aa623669